# Generated by Django 4.2.1
# Run: python manage.py migrate prompt_studio_core_v2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core_v2", "0006_add_custom_data_to_customtool"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="use_vision_table_extraction",
            field=models.BooleanField(
                db_comment="When True, table extraction uses OpenAI vision on the raw document (no x2text).",
                default=False,
            ),
        ),
    ]
